### ISSUE TITLE
Use the tool to get all API versions within a version set?

### ISSUE THREAD

**Issue by joeyeng** [MLogdberg/APIManagementARMTemplateCreator#43]
@MLogdberg @nilshedstrom I was wondering if either of you can answer this question. Using the APIFilters parameter is it possible to pull down all API versions within a single version set? Or are we forced to filter for each API version individually? What I'd like to do is get all versions in a single execution if possible.

**Comment by nilshedstrom** [comment]
I have never used the APIFilters  parameter so I do not know how to use it.

I use Write-APIManagementTemplates with ApiStandalone=true. The result is that I have one master.template.json that will deploy the service, products, groups etc (but no APIs).

For each version set I get a separate directory (api-Calculator) and in that directory there is a api-Calculator.master.template.json that will deploy all the versions of the Calculator.

So I can already deploy all versions of an API without deploying anything else.

**Comment by joeyeng** [comment]
Hm, if you're able to relate each API version back to the parent version set I wonder if it's possible to pull a single version set with all its versions and avoiding pulling down all version sets. Does that make sense?

**Comment by joeyeng** [comment]
Btw, Write-APIManagementTemplates is awesome. I love the way it organizes everything!

**Comment by nilshedstrom** [comment]
Can you explain the problem more: Do you have so many different api-version-sets that it takes to long to generate arm templates for all of them? 
Or is the problem that you want to be able to deploy the different api-versions-sets separately?

**Comment by joeyeng** [comment]
Yes, we have many APIs and many developers. We want everyone to be able to generate their ARM templates quickly and in isolation from the rest of the APIs. So the answer is yes to both questions.

**Comment by MLogdberg** [comment]
So let's see how this works.

Getting things from the REST API is based on retrieving API's and not version sets. The version set is fetched after the API and added to the template.

By default all API's matching the APIFilters is collected from the API.

Example using APIVersion to only generate template for Orders API in the Sales domain.
-APIFilters "path eq 'sales/orders'"
Will collect all API's that has the path sales/orders, this could potentially bee 2-3 verions of this API and all is collected.

If you then want to have even more granular filtering you could us the APIVersion, this filters out so that only the provided version is added to the template. 

Example only collect v2 of the API.
`-ApiVersion v2`

Could that help?

**Comment by joeyeng** [comment]
Thanks, I will try that. Is 'path' the URL suffix? Or the operation path? Or both?

**Comment by joeyeng** [comment]
@MLogdberg I did "path eq '{url suffix}'" and that did the trick - pulled down all versions for the version set. Previously I was using "name" instead of "path" which only pulled down a single version. Thanks! @nilshedstrom I think this method could probably be used with Write-APIManagementTemplates if you just want to generate templates for a single API. Thanks again.
